server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
#    url: "jdbc:mysql://localhost:3306/identity_service"
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
#    username: root
    username: ${DBMS_USER:root}
#    password: root
    password: ${DBMS_PASSWORD:root}
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  signerKey: "JHXmhBfJv6Gx5LHOD4t4P+hBxOo3bO7qxE1v6NUiBgDG2Q1njg+ap+WkMTC8LLTW\n"
  valid-duration: 3600 # in second
  refreshable-duration: 7200 # in second

app:
  services:
    profile: http://localhost:8081/profile