server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/profile-service?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/devhoangpham

idp:
  url: http://localhost:8180
  client-id: devhoangpham
  client-secret: wT0NKYvOmU3U3pW7kmkDnW9d9rdQrqOi